choco install 1password
choco install 7zip
choco install brave
choco install discord
choco install divvy
choco install epicgameslauncher
choco install geforce-experience
choco install goggalaxy
choco install google-backup-and-sync
choco install gpg4win
choco install icue
choco install microsoft-teams
choco install microsoft-windows-terminal
choco install nordvpn
choco install obs
choco install Office365ProPlus
choco install qbittorrent
choco install steam
choco install switcheroo
choco install virtualbox
choco install VisualStudioCode
choco install vlc
choco install wsltty
